CREATE TABLE ecoacme_posts(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES ecoacme_users(id),
    post TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    date_modified TIMESTAMP,
    images TEXT
);

CREATE TABLE ecoacme_comments(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES ecoacme_users(id),
    post_id INTEGER REFERENCES ecoacme_posts(id) ON DELETE CASCADE,
    comments TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    date_modified TIMESTAMP
);

CREATE TABLE ecoacme_messages(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sender_id INTEGER REFERENCES ecoacme_users(id) ,
    receiver_id INTEGER REFERENCES ecoacme_users(id),
    messages TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);

